/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthenticatedSandboxesIndexRouteImport } from './routes/_authenticated/sandboxes/index'
import { Route as AuthenticatedRepositoriesIndexRouteImport } from './routes/_authenticated/repositories/index'
import { Route as AuthenticatedRegistryIndexRouteImport } from './routes/_authenticated/registry/index'
import { Route as AuthenticatedProfilesIndexRouteImport } from './routes/_authenticated/profiles/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSettingsSshKeysRouteImport } from './routes/_authenticated/settings/ssh-keys'
import { Route as AuthenticatedSettingsConnectedAccountsRouteImport } from './routes/_authenticated/settings/connected-accounts'
import { Route as AuthenticatedSandboxesNewRouteImport } from './routes/_authenticated/sandboxes/new'
import { Route as AuthenticatedSandboxesFailedRouteImport } from './routes/_authenticated/sandboxes/failed'
import { Route as AuthenticatedSandboxesActiveRouteImport } from './routes/_authenticated/sandboxes/active'
import { Route as AuthenticatedProfilesCreateRouteImport } from './routes/_authenticated/profiles/create'
import { Route as AuthenticatedGithubSetupRouteImport } from './routes/_authenticated/github/setup'
import { Route as AuthenticatedSandboxesSandboxIdIndexRouteImport } from './routes/_authenticated/sandboxes/$sandboxId/index'
import { Route as AuthenticatedRepositoriesRepoIdIndexRouteImport } from './routes/_authenticated/repositories/$repoId/index'
import { Route as AuthenticatedRegistryRegistryIdIndexRouteImport } from './routes/_authenticated/registry/$registryId/index'
import { Route as AuthenticatedProfilesProfileIdIndexRouteImport } from './routes/_authenticated/profiles/$profileId/index'
import { Route as AuthenticatedSandboxesSandboxIdValidationRouteImport } from './routes/_authenticated/sandboxes/$sandboxId/validation'
import { Route as AuthenticatedSandboxesSandboxIdTraceRouteImport } from './routes/_authenticated/sandboxes/$sandboxId/trace'
import { Route as AuthenticatedSandboxesSandboxIdSpecRouteImport } from './routes/_authenticated/sandboxes/$sandboxId/spec'
import { Route as AuthenticatedSandboxesSandboxIdDiffRouteImport } from './routes/_authenticated/sandboxes/$sandboxId/diff'
import { Route as AuthenticatedRepositoriesRepoIdSetupRouteImport } from './routes/_authenticated/repositories/$repoId/setup'
import { Route as AuthenticatedRepositoriesRepoIdSettingsRouteImport } from './routes/_authenticated/repositories/$repoId/settings'
import { Route as AuthenticatedRepositoriesRepoIdSandboxesRouteImport } from './routes/_authenticated/repositories/$repoId/sandboxes'
import { Route as AuthenticatedProfilesProfileIdSetupRouteImport } from './routes/_authenticated/profiles/$profileId/setup'
import { Route as AuthenticatedProfilesProfileIdSecretsRouteImport } from './routes/_authenticated/profiles/$profileId/secrets'
import { Route as AuthenticatedProfilesProfileIdPackagesRouteImport } from './routes/_authenticated/profiles/$profileId/packages'
import { Route as AuthenticatedProfilesProfileIdEnvVariablesRouteImport } from './routes/_authenticated/profiles/$profileId/env-variables'
import { Route as AuthenticatedProfilesProfileIdAgentsRouteImport } from './routes/_authenticated/profiles/$profileId/agents'
import { Route as AuthenticatedProfilesProfileIdAccessRouteImport } from './routes/_authenticated/profiles/$profileId/access'
import { Route as AuthenticatedSandboxesSandboxIdRunsRunIdRouteImport } from './routes/_authenticated/sandboxes/$sandboxId/runs/$runId'
import { Route as AuthenticatedRegistryRegistryIdRepoTagRouteImport } from './routes/_authenticated/registry/$registryId/$repo/$tag'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSandboxesIndexRoute =
  AuthenticatedSandboxesIndexRouteImport.update({
    id: '/sandboxes/',
    path: '/sandboxes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepositoriesIndexRoute =
  AuthenticatedRepositoriesIndexRouteImport.update({
    id: '/repositories/',
    path: '/repositories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistryIndexRoute =
  AuthenticatedRegistryIndexRouteImport.update({
    id: '/registry/',
    path: '/registry/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilesIndexRoute =
  AuthenticatedProfilesIndexRouteImport.update({
    id: '/profiles/',
    path: '/profiles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsSshKeysRoute =
  AuthenticatedSettingsSshKeysRouteImport.update({
    id: '/settings/ssh-keys',
    path: '/settings/ssh-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsConnectedAccountsRoute =
  AuthenticatedSettingsConnectedAccountsRouteImport.update({
    id: '/settings/connected-accounts',
    path: '/settings/connected-accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxesNewRoute =
  AuthenticatedSandboxesNewRouteImport.update({
    id: '/sandboxes/new',
    path: '/sandboxes/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxesFailedRoute =
  AuthenticatedSandboxesFailedRouteImport.update({
    id: '/sandboxes/failed',
    path: '/sandboxes/failed',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxesActiveRoute =
  AuthenticatedSandboxesActiveRouteImport.update({
    id: '/sandboxes/active',
    path: '/sandboxes/active',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilesCreateRoute =
  AuthenticatedProfilesCreateRouteImport.update({
    id: '/profiles/create',
    path: '/profiles/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGithubSetupRoute =
  AuthenticatedGithubSetupRouteImport.update({
    id: '/github/setup',
    path: '/github/setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxesSandboxIdIndexRoute =
  AuthenticatedSandboxesSandboxIdIndexRouteImport.update({
    id: '/sandboxes/$sandboxId/',
    path: '/sandboxes/$sandboxId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepositoriesRepoIdIndexRoute =
  AuthenticatedRepositoriesRepoIdIndexRouteImport.update({
    id: '/repositories/$repoId/',
    path: '/repositories/$repoId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistryRegistryIdIndexRoute =
  AuthenticatedRegistryRegistryIdIndexRouteImport.update({
    id: '/registry/$registryId/',
    path: '/registry/$registryId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilesProfileIdIndexRoute =
  AuthenticatedProfilesProfileIdIndexRouteImport.update({
    id: '/profiles/$profileId/',
    path: '/profiles/$profileId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxesSandboxIdValidationRoute =
  AuthenticatedSandboxesSandboxIdValidationRouteImport.update({
    id: '/sandboxes/$sandboxId/validation',
    path: '/sandboxes/$sandboxId/validation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxesSandboxIdTraceRoute =
  AuthenticatedSandboxesSandboxIdTraceRouteImport.update({
    id: '/sandboxes/$sandboxId/trace',
    path: '/sandboxes/$sandboxId/trace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxesSandboxIdSpecRoute =
  AuthenticatedSandboxesSandboxIdSpecRouteImport.update({
    id: '/sandboxes/$sandboxId/spec',
    path: '/sandboxes/$sandboxId/spec',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxesSandboxIdDiffRoute =
  AuthenticatedSandboxesSandboxIdDiffRouteImport.update({
    id: '/sandboxes/$sandboxId/diff',
    path: '/sandboxes/$sandboxId/diff',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepositoriesRepoIdSetupRoute =
  AuthenticatedRepositoriesRepoIdSetupRouteImport.update({
    id: '/repositories/$repoId/setup',
    path: '/repositories/$repoId/setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepositoriesRepoIdSettingsRoute =
  AuthenticatedRepositoriesRepoIdSettingsRouteImport.update({
    id: '/repositories/$repoId/settings',
    path: '/repositories/$repoId/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepositoriesRepoIdSandboxesRoute =
  AuthenticatedRepositoriesRepoIdSandboxesRouteImport.update({
    id: '/repositories/$repoId/sandboxes',
    path: '/repositories/$repoId/sandboxes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilesProfileIdSetupRoute =
  AuthenticatedProfilesProfileIdSetupRouteImport.update({
    id: '/profiles/$profileId/setup',
    path: '/profiles/$profileId/setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilesProfileIdSecretsRoute =
  AuthenticatedProfilesProfileIdSecretsRouteImport.update({
    id: '/profiles/$profileId/secrets',
    path: '/profiles/$profileId/secrets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilesProfileIdPackagesRoute =
  AuthenticatedProfilesProfileIdPackagesRouteImport.update({
    id: '/profiles/$profileId/packages',
    path: '/profiles/$profileId/packages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilesProfileIdEnvVariablesRoute =
  AuthenticatedProfilesProfileIdEnvVariablesRouteImport.update({
    id: '/profiles/$profileId/env-variables',
    path: '/profiles/$profileId/env-variables',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilesProfileIdAgentsRoute =
  AuthenticatedProfilesProfileIdAgentsRouteImport.update({
    id: '/profiles/$profileId/agents',
    path: '/profiles/$profileId/agents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilesProfileIdAccessRoute =
  AuthenticatedProfilesProfileIdAccessRouteImport.update({
    id: '/profiles/$profileId/access',
    path: '/profiles/$profileId/access',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSandboxesSandboxIdRunsRunIdRoute =
  AuthenticatedSandboxesSandboxIdRunsRunIdRouteImport.update({
    id: '/sandboxes/$sandboxId/runs/$runId',
    path: '/sandboxes/$sandboxId/runs/$runId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistryRegistryIdRepoTagRoute =
  AuthenticatedRegistryRegistryIdRepoTagRouteImport.update({
    id: '/registry/$registryId/$repo/$tag',
    path: '/registry/$registryId/$repo/$tag',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/setup': typeof SetupRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/about': typeof AuthenticatedAboutRoute
  '/github/setup': typeof AuthenticatedGithubSetupRoute
  '/profiles/create': typeof AuthenticatedProfilesCreateRoute
  '/sandboxes/active': typeof AuthenticatedSandboxesActiveRoute
  '/sandboxes/failed': typeof AuthenticatedSandboxesFailedRoute
  '/sandboxes/new': typeof AuthenticatedSandboxesNewRoute
  '/settings/connected-accounts': typeof AuthenticatedSettingsConnectedAccountsRoute
  '/settings/ssh-keys': typeof AuthenticatedSettingsSshKeysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/profiles/': typeof AuthenticatedProfilesIndexRoute
  '/registry/': typeof AuthenticatedRegistryIndexRoute
  '/repositories/': typeof AuthenticatedRepositoriesIndexRoute
  '/sandboxes/': typeof AuthenticatedSandboxesIndexRoute
  '/profiles/$profileId/access': typeof AuthenticatedProfilesProfileIdAccessRoute
  '/profiles/$profileId/agents': typeof AuthenticatedProfilesProfileIdAgentsRoute
  '/profiles/$profileId/env-variables': typeof AuthenticatedProfilesProfileIdEnvVariablesRoute
  '/profiles/$profileId/packages': typeof AuthenticatedProfilesProfileIdPackagesRoute
  '/profiles/$profileId/secrets': typeof AuthenticatedProfilesProfileIdSecretsRoute
  '/profiles/$profileId/setup': typeof AuthenticatedProfilesProfileIdSetupRoute
  '/repositories/$repoId/sandboxes': typeof AuthenticatedRepositoriesRepoIdSandboxesRoute
  '/repositories/$repoId/settings': typeof AuthenticatedRepositoriesRepoIdSettingsRoute
  '/repositories/$repoId/setup': typeof AuthenticatedRepositoriesRepoIdSetupRoute
  '/sandboxes/$sandboxId/diff': typeof AuthenticatedSandboxesSandboxIdDiffRoute
  '/sandboxes/$sandboxId/spec': typeof AuthenticatedSandboxesSandboxIdSpecRoute
  '/sandboxes/$sandboxId/trace': typeof AuthenticatedSandboxesSandboxIdTraceRoute
  '/sandboxes/$sandboxId/validation': typeof AuthenticatedSandboxesSandboxIdValidationRoute
  '/profiles/$profileId/': typeof AuthenticatedProfilesProfileIdIndexRoute
  '/registry/$registryId/': typeof AuthenticatedRegistryRegistryIdIndexRoute
  '/repositories/$repoId/': typeof AuthenticatedRepositoriesRepoIdIndexRoute
  '/sandboxes/$sandboxId/': typeof AuthenticatedSandboxesSandboxIdIndexRoute
  '/registry/$registryId/$repo/$tag': typeof AuthenticatedRegistryRegistryIdRepoTagRoute
  '/sandboxes/$sandboxId/runs/$runId': typeof AuthenticatedSandboxesSandboxIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/setup': typeof SetupRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/about': typeof AuthenticatedAboutRoute
  '/github/setup': typeof AuthenticatedGithubSetupRoute
  '/profiles/create': typeof AuthenticatedProfilesCreateRoute
  '/sandboxes/active': typeof AuthenticatedSandboxesActiveRoute
  '/sandboxes/failed': typeof AuthenticatedSandboxesFailedRoute
  '/sandboxes/new': typeof AuthenticatedSandboxesNewRoute
  '/settings/connected-accounts': typeof AuthenticatedSettingsConnectedAccountsRoute
  '/settings/ssh-keys': typeof AuthenticatedSettingsSshKeysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/profiles': typeof AuthenticatedProfilesIndexRoute
  '/registry': typeof AuthenticatedRegistryIndexRoute
  '/repositories': typeof AuthenticatedRepositoriesIndexRoute
  '/sandboxes': typeof AuthenticatedSandboxesIndexRoute
  '/profiles/$profileId/access': typeof AuthenticatedProfilesProfileIdAccessRoute
  '/profiles/$profileId/agents': typeof AuthenticatedProfilesProfileIdAgentsRoute
  '/profiles/$profileId/env-variables': typeof AuthenticatedProfilesProfileIdEnvVariablesRoute
  '/profiles/$profileId/packages': typeof AuthenticatedProfilesProfileIdPackagesRoute
  '/profiles/$profileId/secrets': typeof AuthenticatedProfilesProfileIdSecretsRoute
  '/profiles/$profileId/setup': typeof AuthenticatedProfilesProfileIdSetupRoute
  '/repositories/$repoId/sandboxes': typeof AuthenticatedRepositoriesRepoIdSandboxesRoute
  '/repositories/$repoId/settings': typeof AuthenticatedRepositoriesRepoIdSettingsRoute
  '/repositories/$repoId/setup': typeof AuthenticatedRepositoriesRepoIdSetupRoute
  '/sandboxes/$sandboxId/diff': typeof AuthenticatedSandboxesSandboxIdDiffRoute
  '/sandboxes/$sandboxId/spec': typeof AuthenticatedSandboxesSandboxIdSpecRoute
  '/sandboxes/$sandboxId/trace': typeof AuthenticatedSandboxesSandboxIdTraceRoute
  '/sandboxes/$sandboxId/validation': typeof AuthenticatedSandboxesSandboxIdValidationRoute
  '/profiles/$profileId': typeof AuthenticatedProfilesProfileIdIndexRoute
  '/registry/$registryId': typeof AuthenticatedRegistryRegistryIdIndexRoute
  '/repositories/$repoId': typeof AuthenticatedRepositoriesRepoIdIndexRoute
  '/sandboxes/$sandboxId': typeof AuthenticatedSandboxesSandboxIdIndexRoute
  '/registry/$registryId/$repo/$tag': typeof AuthenticatedRegistryRegistryIdRepoTagRoute
  '/sandboxes/$sandboxId/runs/$runId': typeof AuthenticatedSandboxesSandboxIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/setup': typeof SetupRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/github/setup': typeof AuthenticatedGithubSetupRoute
  '/_authenticated/profiles/create': typeof AuthenticatedProfilesCreateRoute
  '/_authenticated/sandboxes/active': typeof AuthenticatedSandboxesActiveRoute
  '/_authenticated/sandboxes/failed': typeof AuthenticatedSandboxesFailedRoute
  '/_authenticated/sandboxes/new': typeof AuthenticatedSandboxesNewRoute
  '/_authenticated/settings/connected-accounts': typeof AuthenticatedSettingsConnectedAccountsRoute
  '/_authenticated/settings/ssh-keys': typeof AuthenticatedSettingsSshKeysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/profiles/': typeof AuthenticatedProfilesIndexRoute
  '/_authenticated/registry/': typeof AuthenticatedRegistryIndexRoute
  '/_authenticated/repositories/': typeof AuthenticatedRepositoriesIndexRoute
  '/_authenticated/sandboxes/': typeof AuthenticatedSandboxesIndexRoute
  '/_authenticated/profiles/$profileId/access': typeof AuthenticatedProfilesProfileIdAccessRoute
  '/_authenticated/profiles/$profileId/agents': typeof AuthenticatedProfilesProfileIdAgentsRoute
  '/_authenticated/profiles/$profileId/env-variables': typeof AuthenticatedProfilesProfileIdEnvVariablesRoute
  '/_authenticated/profiles/$profileId/packages': typeof AuthenticatedProfilesProfileIdPackagesRoute
  '/_authenticated/profiles/$profileId/secrets': typeof AuthenticatedProfilesProfileIdSecretsRoute
  '/_authenticated/profiles/$profileId/setup': typeof AuthenticatedProfilesProfileIdSetupRoute
  '/_authenticated/repositories/$repoId/sandboxes': typeof AuthenticatedRepositoriesRepoIdSandboxesRoute
  '/_authenticated/repositories/$repoId/settings': typeof AuthenticatedRepositoriesRepoIdSettingsRoute
  '/_authenticated/repositories/$repoId/setup': typeof AuthenticatedRepositoriesRepoIdSetupRoute
  '/_authenticated/sandboxes/$sandboxId/diff': typeof AuthenticatedSandboxesSandboxIdDiffRoute
  '/_authenticated/sandboxes/$sandboxId/spec': typeof AuthenticatedSandboxesSandboxIdSpecRoute
  '/_authenticated/sandboxes/$sandboxId/trace': typeof AuthenticatedSandboxesSandboxIdTraceRoute
  '/_authenticated/sandboxes/$sandboxId/validation': typeof AuthenticatedSandboxesSandboxIdValidationRoute
  '/_authenticated/profiles/$profileId/': typeof AuthenticatedProfilesProfileIdIndexRoute
  '/_authenticated/registry/$registryId/': typeof AuthenticatedRegistryRegistryIdIndexRoute
  '/_authenticated/repositories/$repoId/': typeof AuthenticatedRepositoriesRepoIdIndexRoute
  '/_authenticated/sandboxes/$sandboxId/': typeof AuthenticatedSandboxesSandboxIdIndexRoute
  '/_authenticated/registry/$registryId/$repo/$tag': typeof AuthenticatedRegistryRegistryIdRepoTagRoute
  '/_authenticated/sandboxes/$sandboxId/runs/$runId': typeof AuthenticatedSandboxesSandboxIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/about'
    | '/github/setup'
    | '/profiles/create'
    | '/sandboxes/active'
    | '/sandboxes/failed'
    | '/sandboxes/new'
    | '/settings/connected-accounts'
    | '/settings/ssh-keys'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/profiles/'
    | '/registry/'
    | '/repositories/'
    | '/sandboxes/'
    | '/profiles/$profileId/access'
    | '/profiles/$profileId/agents'
    | '/profiles/$profileId/env-variables'
    | '/profiles/$profileId/packages'
    | '/profiles/$profileId/secrets'
    | '/profiles/$profileId/setup'
    | '/repositories/$repoId/sandboxes'
    | '/repositories/$repoId/settings'
    | '/repositories/$repoId/setup'
    | '/sandboxes/$sandboxId/diff'
    | '/sandboxes/$sandboxId/spec'
    | '/sandboxes/$sandboxId/trace'
    | '/sandboxes/$sandboxId/validation'
    | '/profiles/$profileId/'
    | '/registry/$registryId/'
    | '/repositories/$repoId/'
    | '/sandboxes/$sandboxId/'
    | '/registry/$registryId/$repo/$tag'
    | '/sandboxes/$sandboxId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/about'
    | '/github/setup'
    | '/profiles/create'
    | '/sandboxes/active'
    | '/sandboxes/failed'
    | '/sandboxes/new'
    | '/settings/connected-accounts'
    | '/settings/ssh-keys'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/profiles'
    | '/registry'
    | '/repositories'
    | '/sandboxes'
    | '/profiles/$profileId/access'
    | '/profiles/$profileId/agents'
    | '/profiles/$profileId/env-variables'
    | '/profiles/$profileId/packages'
    | '/profiles/$profileId/secrets'
    | '/profiles/$profileId/setup'
    | '/repositories/$repoId/sandboxes'
    | '/repositories/$repoId/settings'
    | '/repositories/$repoId/setup'
    | '/sandboxes/$sandboxId/diff'
    | '/sandboxes/$sandboxId/spec'
    | '/sandboxes/$sandboxId/trace'
    | '/sandboxes/$sandboxId/validation'
    | '/profiles/$profileId'
    | '/registry/$registryId'
    | '/repositories/$repoId'
    | '/sandboxes/$sandboxId'
    | '/registry/$registryId/$repo/$tag'
    | '/sandboxes/$sandboxId/runs/$runId'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/setup'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_authenticated/about'
    | '/_authenticated/'
    | '/_authenticated/github/setup'
    | '/_authenticated/profiles/create'
    | '/_authenticated/sandboxes/active'
    | '/_authenticated/sandboxes/failed'
    | '/_authenticated/sandboxes/new'
    | '/_authenticated/settings/connected-accounts'
    | '/_authenticated/settings/ssh-keys'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authenticated/profiles/'
    | '/_authenticated/registry/'
    | '/_authenticated/repositories/'
    | '/_authenticated/sandboxes/'
    | '/_authenticated/profiles/$profileId/access'
    | '/_authenticated/profiles/$profileId/agents'
    | '/_authenticated/profiles/$profileId/env-variables'
    | '/_authenticated/profiles/$profileId/packages'
    | '/_authenticated/profiles/$profileId/secrets'
    | '/_authenticated/profiles/$profileId/setup'
    | '/_authenticated/repositories/$repoId/sandboxes'
    | '/_authenticated/repositories/$repoId/settings'
    | '/_authenticated/repositories/$repoId/setup'
    | '/_authenticated/sandboxes/$sandboxId/diff'
    | '/_authenticated/sandboxes/$sandboxId/spec'
    | '/_authenticated/sandboxes/$sandboxId/trace'
    | '/_authenticated/sandboxes/$sandboxId/validation'
    | '/_authenticated/profiles/$profileId/'
    | '/_authenticated/registry/$registryId/'
    | '/_authenticated/repositories/$repoId/'
    | '/_authenticated/sandboxes/$sandboxId/'
    | '/_authenticated/registry/$registryId/$repo/$tag'
    | '/_authenticated/sandboxes/$sandboxId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SetupRoute: typeof SetupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/sandboxes/': {
      id: '/_authenticated/sandboxes/'
      path: '/sandboxes'
      fullPath: '/sandboxes/'
      preLoaderRoute: typeof AuthenticatedSandboxesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repositories/': {
      id: '/_authenticated/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof AuthenticatedRepositoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registry/': {
      id: '/_authenticated/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof AuthenticatedRegistryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/': {
      id: '/_authenticated/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof AuthenticatedProfilesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/ssh-keys': {
      id: '/_authenticated/settings/ssh-keys'
      path: '/settings/ssh-keys'
      fullPath: '/settings/ssh-keys'
      preLoaderRoute: typeof AuthenticatedSettingsSshKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/connected-accounts': {
      id: '/_authenticated/settings/connected-accounts'
      path: '/settings/connected-accounts'
      fullPath: '/settings/connected-accounts'
      preLoaderRoute: typeof AuthenticatedSettingsConnectedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandboxes/new': {
      id: '/_authenticated/sandboxes/new'
      path: '/sandboxes/new'
      fullPath: '/sandboxes/new'
      preLoaderRoute: typeof AuthenticatedSandboxesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandboxes/failed': {
      id: '/_authenticated/sandboxes/failed'
      path: '/sandboxes/failed'
      fullPath: '/sandboxes/failed'
      preLoaderRoute: typeof AuthenticatedSandboxesFailedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandboxes/active': {
      id: '/_authenticated/sandboxes/active'
      path: '/sandboxes/active'
      fullPath: '/sandboxes/active'
      preLoaderRoute: typeof AuthenticatedSandboxesActiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/create': {
      id: '/_authenticated/profiles/create'
      path: '/profiles/create'
      fullPath: '/profiles/create'
      preLoaderRoute: typeof AuthenticatedProfilesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/github/setup': {
      id: '/_authenticated/github/setup'
      path: '/github/setup'
      fullPath: '/github/setup'
      preLoaderRoute: typeof AuthenticatedGithubSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandboxes/$sandboxId/': {
      id: '/_authenticated/sandboxes/$sandboxId/'
      path: '/sandboxes/$sandboxId'
      fullPath: '/sandboxes/$sandboxId/'
      preLoaderRoute: typeof AuthenticatedSandboxesSandboxIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repositories/$repoId/': {
      id: '/_authenticated/repositories/$repoId/'
      path: '/repositories/$repoId'
      fullPath: '/repositories/$repoId/'
      preLoaderRoute: typeof AuthenticatedRepositoriesRepoIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registry/$registryId/': {
      id: '/_authenticated/registry/$registryId/'
      path: '/registry/$registryId'
      fullPath: '/registry/$registryId/'
      preLoaderRoute: typeof AuthenticatedRegistryRegistryIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/$profileId/': {
      id: '/_authenticated/profiles/$profileId/'
      path: '/profiles/$profileId'
      fullPath: '/profiles/$profileId/'
      preLoaderRoute: typeof AuthenticatedProfilesProfileIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandboxes/$sandboxId/validation': {
      id: '/_authenticated/sandboxes/$sandboxId/validation'
      path: '/sandboxes/$sandboxId/validation'
      fullPath: '/sandboxes/$sandboxId/validation'
      preLoaderRoute: typeof AuthenticatedSandboxesSandboxIdValidationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandboxes/$sandboxId/trace': {
      id: '/_authenticated/sandboxes/$sandboxId/trace'
      path: '/sandboxes/$sandboxId/trace'
      fullPath: '/sandboxes/$sandboxId/trace'
      preLoaderRoute: typeof AuthenticatedSandboxesSandboxIdTraceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandboxes/$sandboxId/spec': {
      id: '/_authenticated/sandboxes/$sandboxId/spec'
      path: '/sandboxes/$sandboxId/spec'
      fullPath: '/sandboxes/$sandboxId/spec'
      preLoaderRoute: typeof AuthenticatedSandboxesSandboxIdSpecRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandboxes/$sandboxId/diff': {
      id: '/_authenticated/sandboxes/$sandboxId/diff'
      path: '/sandboxes/$sandboxId/diff'
      fullPath: '/sandboxes/$sandboxId/diff'
      preLoaderRoute: typeof AuthenticatedSandboxesSandboxIdDiffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repositories/$repoId/setup': {
      id: '/_authenticated/repositories/$repoId/setup'
      path: '/repositories/$repoId/setup'
      fullPath: '/repositories/$repoId/setup'
      preLoaderRoute: typeof AuthenticatedRepositoriesRepoIdSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repositories/$repoId/settings': {
      id: '/_authenticated/repositories/$repoId/settings'
      path: '/repositories/$repoId/settings'
      fullPath: '/repositories/$repoId/settings'
      preLoaderRoute: typeof AuthenticatedRepositoriesRepoIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repositories/$repoId/sandboxes': {
      id: '/_authenticated/repositories/$repoId/sandboxes'
      path: '/repositories/$repoId/sandboxes'
      fullPath: '/repositories/$repoId/sandboxes'
      preLoaderRoute: typeof AuthenticatedRepositoriesRepoIdSandboxesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/$profileId/setup': {
      id: '/_authenticated/profiles/$profileId/setup'
      path: '/profiles/$profileId/setup'
      fullPath: '/profiles/$profileId/setup'
      preLoaderRoute: typeof AuthenticatedProfilesProfileIdSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/$profileId/secrets': {
      id: '/_authenticated/profiles/$profileId/secrets'
      path: '/profiles/$profileId/secrets'
      fullPath: '/profiles/$profileId/secrets'
      preLoaderRoute: typeof AuthenticatedProfilesProfileIdSecretsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/$profileId/packages': {
      id: '/_authenticated/profiles/$profileId/packages'
      path: '/profiles/$profileId/packages'
      fullPath: '/profiles/$profileId/packages'
      preLoaderRoute: typeof AuthenticatedProfilesProfileIdPackagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/$profileId/env-variables': {
      id: '/_authenticated/profiles/$profileId/env-variables'
      path: '/profiles/$profileId/env-variables'
      fullPath: '/profiles/$profileId/env-variables'
      preLoaderRoute: typeof AuthenticatedProfilesProfileIdEnvVariablesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/$profileId/agents': {
      id: '/_authenticated/profiles/$profileId/agents'
      path: '/profiles/$profileId/agents'
      fullPath: '/profiles/$profileId/agents'
      preLoaderRoute: typeof AuthenticatedProfilesProfileIdAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles/$profileId/access': {
      id: '/_authenticated/profiles/$profileId/access'
      path: '/profiles/$profileId/access'
      fullPath: '/profiles/$profileId/access'
      preLoaderRoute: typeof AuthenticatedProfilesProfileIdAccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sandboxes/$sandboxId/runs/$runId': {
      id: '/_authenticated/sandboxes/$sandboxId/runs/$runId'
      path: '/sandboxes/$sandboxId/runs/$runId'
      fullPath: '/sandboxes/$sandboxId/runs/$runId'
      preLoaderRoute: typeof AuthenticatedSandboxesSandboxIdRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registry/$registryId/$repo/$tag': {
      id: '/_authenticated/registry/$registryId/$repo/$tag'
      path: '/registry/$registryId/$repo/$tag'
      fullPath: '/registry/$registryId/$repo/$tag'
      preLoaderRoute: typeof AuthenticatedRegistryRegistryIdRepoTagRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGithubSetupRoute: typeof AuthenticatedGithubSetupRoute
  AuthenticatedProfilesCreateRoute: typeof AuthenticatedProfilesCreateRoute
  AuthenticatedSandboxesActiveRoute: typeof AuthenticatedSandboxesActiveRoute
  AuthenticatedSandboxesFailedRoute: typeof AuthenticatedSandboxesFailedRoute
  AuthenticatedSandboxesNewRoute: typeof AuthenticatedSandboxesNewRoute
  AuthenticatedSettingsConnectedAccountsRoute: typeof AuthenticatedSettingsConnectedAccountsRoute
  AuthenticatedSettingsSshKeysRoute: typeof AuthenticatedSettingsSshKeysRoute
  AuthenticatedProfilesIndexRoute: typeof AuthenticatedProfilesIndexRoute
  AuthenticatedRegistryIndexRoute: typeof AuthenticatedRegistryIndexRoute
  AuthenticatedRepositoriesIndexRoute: typeof AuthenticatedRepositoriesIndexRoute
  AuthenticatedSandboxesIndexRoute: typeof AuthenticatedSandboxesIndexRoute
  AuthenticatedProfilesProfileIdAccessRoute: typeof AuthenticatedProfilesProfileIdAccessRoute
  AuthenticatedProfilesProfileIdAgentsRoute: typeof AuthenticatedProfilesProfileIdAgentsRoute
  AuthenticatedProfilesProfileIdEnvVariablesRoute: typeof AuthenticatedProfilesProfileIdEnvVariablesRoute
  AuthenticatedProfilesProfileIdPackagesRoute: typeof AuthenticatedProfilesProfileIdPackagesRoute
  AuthenticatedProfilesProfileIdSecretsRoute: typeof AuthenticatedProfilesProfileIdSecretsRoute
  AuthenticatedProfilesProfileIdSetupRoute: typeof AuthenticatedProfilesProfileIdSetupRoute
  AuthenticatedRepositoriesRepoIdSandboxesRoute: typeof AuthenticatedRepositoriesRepoIdSandboxesRoute
  AuthenticatedRepositoriesRepoIdSettingsRoute: typeof AuthenticatedRepositoriesRepoIdSettingsRoute
  AuthenticatedRepositoriesRepoIdSetupRoute: typeof AuthenticatedRepositoriesRepoIdSetupRoute
  AuthenticatedSandboxesSandboxIdDiffRoute: typeof AuthenticatedSandboxesSandboxIdDiffRoute
  AuthenticatedSandboxesSandboxIdSpecRoute: typeof AuthenticatedSandboxesSandboxIdSpecRoute
  AuthenticatedSandboxesSandboxIdTraceRoute: typeof AuthenticatedSandboxesSandboxIdTraceRoute
  AuthenticatedSandboxesSandboxIdValidationRoute: typeof AuthenticatedSandboxesSandboxIdValidationRoute
  AuthenticatedProfilesProfileIdIndexRoute: typeof AuthenticatedProfilesProfileIdIndexRoute
  AuthenticatedRegistryRegistryIdIndexRoute: typeof AuthenticatedRegistryRegistryIdIndexRoute
  AuthenticatedRepositoriesRepoIdIndexRoute: typeof AuthenticatedRepositoriesRepoIdIndexRoute
  AuthenticatedSandboxesSandboxIdIndexRoute: typeof AuthenticatedSandboxesSandboxIdIndexRoute
  AuthenticatedRegistryRegistryIdRepoTagRoute: typeof AuthenticatedRegistryRegistryIdRepoTagRoute
  AuthenticatedSandboxesSandboxIdRunsRunIdRoute: typeof AuthenticatedSandboxesSandboxIdRunsRunIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGithubSetupRoute: AuthenticatedGithubSetupRoute,
  AuthenticatedProfilesCreateRoute: AuthenticatedProfilesCreateRoute,
  AuthenticatedSandboxesActiveRoute: AuthenticatedSandboxesActiveRoute,
  AuthenticatedSandboxesFailedRoute: AuthenticatedSandboxesFailedRoute,
  AuthenticatedSandboxesNewRoute: AuthenticatedSandboxesNewRoute,
  AuthenticatedSettingsConnectedAccountsRoute:
    AuthenticatedSettingsConnectedAccountsRoute,
  AuthenticatedSettingsSshKeysRoute: AuthenticatedSettingsSshKeysRoute,
  AuthenticatedProfilesIndexRoute: AuthenticatedProfilesIndexRoute,
  AuthenticatedRegistryIndexRoute: AuthenticatedRegistryIndexRoute,
  AuthenticatedRepositoriesIndexRoute: AuthenticatedRepositoriesIndexRoute,
  AuthenticatedSandboxesIndexRoute: AuthenticatedSandboxesIndexRoute,
  AuthenticatedProfilesProfileIdAccessRoute:
    AuthenticatedProfilesProfileIdAccessRoute,
  AuthenticatedProfilesProfileIdAgentsRoute:
    AuthenticatedProfilesProfileIdAgentsRoute,
  AuthenticatedProfilesProfileIdEnvVariablesRoute:
    AuthenticatedProfilesProfileIdEnvVariablesRoute,
  AuthenticatedProfilesProfileIdPackagesRoute:
    AuthenticatedProfilesProfileIdPackagesRoute,
  AuthenticatedProfilesProfileIdSecretsRoute:
    AuthenticatedProfilesProfileIdSecretsRoute,
  AuthenticatedProfilesProfileIdSetupRoute:
    AuthenticatedProfilesProfileIdSetupRoute,
  AuthenticatedRepositoriesRepoIdSandboxesRoute:
    AuthenticatedRepositoriesRepoIdSandboxesRoute,
  AuthenticatedRepositoriesRepoIdSettingsRoute:
    AuthenticatedRepositoriesRepoIdSettingsRoute,
  AuthenticatedRepositoriesRepoIdSetupRoute:
    AuthenticatedRepositoriesRepoIdSetupRoute,
  AuthenticatedSandboxesSandboxIdDiffRoute:
    AuthenticatedSandboxesSandboxIdDiffRoute,
  AuthenticatedSandboxesSandboxIdSpecRoute:
    AuthenticatedSandboxesSandboxIdSpecRoute,
  AuthenticatedSandboxesSandboxIdTraceRoute:
    AuthenticatedSandboxesSandboxIdTraceRoute,
  AuthenticatedSandboxesSandboxIdValidationRoute:
    AuthenticatedSandboxesSandboxIdValidationRoute,
  AuthenticatedProfilesProfileIdIndexRoute:
    AuthenticatedProfilesProfileIdIndexRoute,
  AuthenticatedRegistryRegistryIdIndexRoute:
    AuthenticatedRegistryRegistryIdIndexRoute,
  AuthenticatedRepositoriesRepoIdIndexRoute:
    AuthenticatedRepositoriesRepoIdIndexRoute,
  AuthenticatedSandboxesSandboxIdIndexRoute:
    AuthenticatedSandboxesSandboxIdIndexRoute,
  AuthenticatedRegistryRegistryIdRepoTagRoute:
    AuthenticatedRegistryRegistryIdRepoTagRoute,
  AuthenticatedSandboxesSandboxIdRunsRunIdRoute:
    AuthenticatedSandboxesSandboxIdRunsRunIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SetupRoute: SetupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
