/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistryIndexRouteImport } from './routes/registry/index'
import { Route as RegistryRegistryIdIndexRouteImport } from './routes/registry/$registryId/index'
import { Route as RegistryRegistryIdRepoTagRouteImport } from './routes/registry/$registryId/$repo/$tag'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRegistryIdIndexRoute = RegistryRegistryIdIndexRouteImport.update({
  id: '/registry/$registryId/',
  path: '/registry/$registryId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRegistryIdRepoTagRoute =
  RegistryRegistryIdRepoTagRouteImport.update({
    id: '/registry/$registryId/$repo/$tag',
    path: '/registry/$registryId/$repo/$tag',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/registry/': typeof RegistryIndexRoute
  '/registry/$registryId/': typeof RegistryRegistryIdIndexRoute
  '/registry/$registryId/$repo/$tag': typeof RegistryRegistryIdRepoTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/registry': typeof RegistryIndexRoute
  '/registry/$registryId': typeof RegistryRegistryIdIndexRoute
  '/registry/$registryId/$repo/$tag': typeof RegistryRegistryIdRepoTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/registry/': typeof RegistryIndexRoute
  '/registry/$registryId/': typeof RegistryRegistryIdIndexRoute
  '/registry/$registryId/$repo/$tag': typeof RegistryRegistryIdRepoTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/registry/'
    | '/registry/$registryId/'
    | '/registry/$registryId/$repo/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/registry'
    | '/registry/$registryId'
    | '/registry/$registryId/$repo/$tag'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/registry/'
    | '/registry/$registryId/'
    | '/registry/$registryId/$repo/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
  RegistryRegistryIdIndexRoute: typeof RegistryRegistryIdIndexRoute
  RegistryRegistryIdRepoTagRoute: typeof RegistryRegistryIdRepoTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/': {
      id: '/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$registryId/': {
      id: '/registry/$registryId/'
      path: '/registry/$registryId'
      fullPath: '/registry/$registryId/'
      preLoaderRoute: typeof RegistryRegistryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$registryId/$repo/$tag': {
      id: '/registry/$registryId/$repo/$tag'
      path: '/registry/$registryId/$repo/$tag'
      fullPath: '/registry/$registryId/$repo/$tag'
      preLoaderRoute: typeof RegistryRegistryIdRepoTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RegistryIndexRoute: RegistryIndexRoute,
  RegistryRegistryIdIndexRoute: RegistryRegistryIdIndexRoute,
  RegistryRegistryIdRepoTagRoute: RegistryRegistryIdRepoTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
