export {
  CredentialCipher,
  CredentialCipherConfig,
  CredentialCipherError,
  CredentialCipherLive,
  credentialCipherLayer,
  SEALED_CREDENTIAL_VERSION,
  sha256Hex,
  type CredentialCipherOperation,
  type CredentialCipherOptions,
  type CredentialCipherService,
  type SealedCredential,
} from "./cipher.js";

export {
  CLAUDE_CONFIG_DIR_ENV_KEY,
  CLAUDE_CREDENTIALS_FILE_NAME,
  isNewerClaudeCredentials,
  isPlausibleClaudeExpiry,
  MAX_PLAUSIBLE_CLAUDE_EXPIRY_AHEAD_MS,
  provisionClaudeConfigDir,
  readClaudeConfigDirCredentials,
  readStoredClaudeExpiresAt,
  removeClaudeConfigDir,
  type ProvisionedClaudeConfigDir,
} from "./claude-session.js";

export {
  CODEX_AUTH_FILE_NAME,
  CODEX_HOME_ENV_KEY,
  provisionCodexHome,
  readCodexHomeAuthJson,
  removeCodexHome,
  type ProvisionedCodexHome,
} from "./codex-session.js";

export {
  CLAUDE_CREDENTIALS_JSON_PATH,
  CLAUDE_OAUTH_TOKEN_ENV_KEY,
  CODEX_AUTH_JSON_PATH,
  CONNECTED_ACCOUNT_REF_PREFIX,
  createConnectedAccountRef,
  GITHUB_TOKEN_ENV_KEYS,
  parseConnectedAccountRef,
  planCredentialInjections,
  type CredentialInjection,
} from "./injection.js";

export {
  CLAUDE_TOKEN_PREFIX,
  claudeCredentialPayloadSchema,
  claudeCredentialsFilePayloadSchema,
  claudeTokenCredentialPayloadSchema,
  codexCredentialPayloadSchema,
  connectedAccountProviders,
  connectedAccountProviderSchema,
  extractClaudeOauthCredentials,
  extractCodexSecrets,
  GITHUB_TOKEN_PREFIXES,
  githubCredentialPayloadSchema,
  hasKnownGitHubTokenPrefix,
  parseClaudeCredentialPayload,
  parseClaudeCredentialsFilePayload,
  parseClaudeCredentialsJson,
  parseCodexAuthJson,
  parseCodexCredentialPayload,
  parseGitHubCredentialPayload,
  type ClaudeCredentialPayload,
  type ClaudeCredentialsFilePayload,
  type ClaudeCredentialsMetadata,
  type ClaudeOauthCredentials,
  type ClaudeTokenCredentialPayload,
  type CodexAuthMetadata,
  type CodexCredentialPayload,
  type ConnectedAccountProvider,
  type GitHubCredentialPayload,
  type ParseClaudeCredentialsJsonResult,
  type ParseCodexAuthJsonResult,
} from "./payloads.js";
