/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V5RouteImport } from './routes/v5'
import { Route as V4RouteImport } from './routes/v4'
import { Route as V3RouteImport } from './routes/v3'
import { Route as V2RouteImport } from './routes/v2'
import { Route as IndexRouteImport } from './routes/index'

const V5Route = V5RouteImport.update({
  id: '/v5',
  path: '/v5',
  getParentRoute: () => rootRouteImport,
} as any)
const V4Route = V4RouteImport.update({
  id: '/v4',
  path: '/v4',
  getParentRoute: () => rootRouteImport,
} as any)
const V3Route = V3RouteImport.update({
  id: '/v3',
  path: '/v3',
  getParentRoute: () => rootRouteImport,
} as any)
const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/v2': typeof V2Route
  '/v3': typeof V3Route
  '/v4': typeof V4Route
  '/v5': typeof V5Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/v2': typeof V2Route
  '/v3': typeof V3Route
  '/v4': typeof V4Route
  '/v5': typeof V5Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/v2': typeof V2Route
  '/v3': typeof V3Route
  '/v4': typeof V4Route
  '/v5': typeof V5Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/v2' | '/v3' | '/v4' | '/v5'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/v2' | '/v3' | '/v4' | '/v5'
  id: '__root__' | '/' | '/v2' | '/v3' | '/v4' | '/v5'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  V2Route: typeof V2Route
  V3Route: typeof V3Route
  V4Route: typeof V4Route
  V5Route: typeof V5Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v5': {
      id: '/v5'
      path: '/v5'
      fullPath: '/v5'
      preLoaderRoute: typeof V5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4': {
      id: '/v4'
      path: '/v4'
      fullPath: '/v4'
      preLoaderRoute: typeof V4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3': {
      id: '/v3'
      path: '/v3'
      fullPath: '/v3'
      preLoaderRoute: typeof V3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  V2Route: V2Route,
  V3Route: V3Route,
  V4Route: V4Route,
  V5Route: V5Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
